package com.vicayala.responsible.infrastructure.bd.entities.responsible;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.vicayala.responsible.domain.dtos.responsible.BranchResponsibleDTO;
import com.vicayala.responsible.domain.dtos.responsible.ContractEmployeeResponsibleDTO;
import com.vicayala.responsible.domain.dtos.responsible.InHouseEmployeeResponsibleDTO;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

import java.io.Serializable;

@SuperBuilder(toBuilder = true)
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString
@JsonTypeInfo(use = JsonTypeInfo.Id.DEDUCTION)
@JsonSubTypes({
        @JsonSubTypes.Type(value = ContractEmployeeResponsibleEntity.class, name = ContractEmployeeResponsibleDTO.TYPE),
        @JsonSubTypes.Type(value = InHouseEmployeeResponsibleEntity.class, name = InHouseEmployeeResponsibleDTO.TYPE),
        @JsonSubTypes.Type(value = BranchResponsibleEntity.class, name = BranchResponsibleDTO.TYPE)
})
@DynamoDBTable(tableName = "help-center-responsible")
public abstract class ResponsibleEntity implements Serializable {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;
    @DynamoDBAttribute(attributeName = "responsibleType")
    private String responsibleType;

}
